#:schema node_modules/wrangler/config-schema.json
name = "pollibazar"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages Build Output Directory
pages_build_output_dir = "dist"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "pollibazar-db"
database_id = "c5cc8d6a-cb1c-44b9-a8d1-b39b364aa950"
migrations_dir = "migrations"

# Environment Variables
[vars]
ENVIRONMENT = "production"
SITE_NAME = "PolliBazar"
SITE_URL = "https://pollibazar.pages.dev"
